// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACZPxJwFFXgTvbC-PI3-eT3i39SngSEto',
    appId: '1:64779467379:web:b6e4c5c88d97c3b2568806',
    messagingSenderId: '64779467379',
    projectId: 'fl-stage-882f0',
    authDomain: 'fl-stage-882f0.firebaseapp.com',
    storageBucket: 'fl-stage-882f0.appspot.com',
    measurementId: 'G-7RVYGX3JBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkMBBVO6ZioNrK457co3d6i79AVaGQ93o',
    appId: '1:64779467379:android:3e9095691a905940568806',
    messagingSenderId: '64779467379',
    projectId: 'fl-stage-882f0',
    storageBucket: 'fl-stage-882f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPhu7_oz5tjAis96NN8-B4QydAw8bn6s',
    appId: '1:64779467379:ios:7b6eda41721a6dc8568806',
    messagingSenderId: '64779467379',
    projectId: 'fl-stage-882f0',
    storageBucket: 'fl-stage-882f0.appspot.com',
    iosClientId: '64779467379-fe9s8hemnuc4adgvqertbj3o28694ndb.apps.googleusercontent.com',
    iosBundleId: 'com.demoappflavor.stg',
  );
}
