// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7yGOOkCcxYeHYz9a0vJsydwgiqvcqyE',
    appId: '1:90783123329:web:c8e436ea63529f3ffaca80',
    messagingSenderId: '90783123329',
    projectId: 'fl-dev-a1ccb',
    authDomain: 'fl-dev-a1ccb.firebaseapp.com',
    storageBucket: 'fl-dev-a1ccb.appspot.com',
    measurementId: 'G-T49MJEL9B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3aG0ZEkv62t8Cbs_2zRnH3Vqb2X_AYk',
    appId: '1:90783123329:android:be4444e3e92ed5b1faca80',
    messagingSenderId: '90783123329',
    projectId: 'fl-dev-a1ccb',
    storageBucket: 'fl-dev-a1ccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFAXDHLihlvVpw1X8M5LVC5ChltVbSnI',
    appId: '1:90783123329:ios:a894ffb06f81fd42faca80',
    messagingSenderId: '90783123329',
    projectId: 'fl-dev-a1ccb',
    storageBucket: 'fl-dev-a1ccb.appspot.com',
    iosClientId: '90783123329-bk1kfvu259gbi8hnnf85fjsesb2613h6.apps.googleusercontent.com',
    iosBundleId: 'com.demoappflavor.dev',
  );
}
