// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBa7XluT3RFWXB4orSv9m73oVyyPLk4hQ',
    appId: '1:447431521798:web:203dfcef0f6fd75073f587',
    messagingSenderId: '447431521798',
    projectId: 'fl-prod-77f01',
    authDomain: 'fl-prod-77f01.firebaseapp.com',
    storageBucket: 'fl-prod-77f01.appspot.com',
    measurementId: 'G-24BGYWHBRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVOFpmWmNYu394E-V4mU530DBQxDaslE',
    appId: '1:447431521798:android:35e502d1d8a041d073f587',
    messagingSenderId: '447431521798',
    projectId: 'fl-prod-77f01',
    storageBucket: 'fl-prod-77f01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaw3aJX2S0Hm6BR36OuswGUOnbeIFbeA8',
    appId: '1:447431521798:ios:7106350afb8429cc73f587',
    messagingSenderId: '447431521798',
    projectId: 'fl-prod-77f01',
    storageBucket: 'fl-prod-77f01.appspot.com',
    iosClientId: '447431521798-3s1hir7ds9pbfdfoni5hv3lhl5ir8h4c.apps.googleusercontent.com',
    iosBundleId: 'com.demoappflavor',
  );
}
